package config

const (
	BASIC_AUTH_USER         = "BASIC_AUTH_USER"
	BASIC_AUTH_PASS         = "BASIC_AUTH_PASS"
	IS_DEV                  = "IS_DEV"
	PUBLIC_WEB_SERVER_PORT  = "PUBLIC_WEB_SERVER_PORT"
	METRICS_WEB_SERVER_PORT = "METRICS_WEB_SERVER_PORT"
	PPROF_WEB_SERVER_PORT   = "PPROF_WEB_SERVER_PORT"
)
